# Generated by Django 3.1.5 on 2021-01-30 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgnt', '0002_auto_20210130_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='export_to_CSV',
        ),
    ]
