# Generated by Django 3.1.5 on 2021-01-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgnt', '0005_auto_20210130_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
