# Generated by Django 3.1.6 on 2021-02-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgnt', '0008_stockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('message', models.TextField()),
            ],
        ),
    ]
