# Generated by Django 3.1.6 on 2021-02-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgnt', '0009_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
